name: term_glyph
version: 1.1.1-dev

description: Useful Unicode glyphs and ASCII substitutes.
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/term_glyph

environment:
  sdk: '>=2.8.0-dev.10 <3.0.0'

dev_dependencies:
  csv: '>=3.0.0 <5.0.0'
  dart_style: '>=0.2.0 <2.0.0'
  test: '>=0.12.0 <2.0.0'

dependency_overrides:
  boolean_selector:
    git:
      url: git://github.com/dart-lang/boolean_selector.git
      ref: null_safety
  charcode:
    git:
      url: git://github.com/dart-lang/charcode.git
      ref: null_safety
  matcher:
    git:
      url: git://github.com/dart-lang/matcher.git
      ref: null_safety
  path:
    git:
      url: git://github.com/dart-lang/path.git
      ref: null_safety_insert_workaround
  source_span:
    git:
      url: git://github.com/dart-lang/source_span.git
      ref: null_safety
  stack_trace:
    git:
      url: git://github.com/dart-lang/stack_trace.git
      ref: null_safety
  string_scanner:
    git:
      url: git://github.com/dart-lang/string_scanner.git
      ref: null_safety
  test_api:
    git:
      url: git://github.com/dart-lang/test.git
      ref: null_safety
      path: pkgs/test_api