name: term_glyph
version: 1.1.1-dev

description: Useful Unicode glyphs and ASCII substitutes.
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/term_glyph

environment:
  sdk: '>=2.8.0-dev.10 <3.0.0'

dev_dependencies:
  csv: '>=3.0.0 <5.0.0'
  dart_style: '>=0.2.0 <2.0.0'
  test: '>=0.12.0 <2.0.0'
